spring:
  application:
    name: mga-back-asignacion-automatica
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:laProveta
    username: laProveta
    password: laProveta
    driver-class-name: org.h2.Driver
    hikari:
      idle-timeout: 10000
      minimum-idle: 2
      maximum-pool-size: 10
      max-lifetime: 30000
  jpa:
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          lock:
            timeout: 25000
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
